config/routes.rb
EvolveYourself::Application.routes.draw do
  
	ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

	match "story" => "colophon#story"
  root :to => 'colophon#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  #attr_accessible :title, :body

	has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

	scope :feature, where(:featured => true)
 
	attr_accessible :title, :body, :featured, :excerpt, :vimeo, :slug
	validates_presence_of :title, :body, :excerpt
		
	extend FriendlyId
  friendly_id :title, use: :slugged

	belongs_to :user
	before_save :assert_featured

	def assert_featured
    if self.featured?
      Post.where('id != ?',self.id).each do |post|
        post.featured = false
        post.save!
      end
    end
  end
      
end

app/models/tag.rb
class Tag < ActiveRecord::Base

	attr_accessible :title
	validates_presence_of :title
	
	has_and_belongs_to_many :videos

end

app/models/video.rb
class Video < ActiveRecord::Base

	attr_accessible :vimeo, :tag_ids, :featured
	validates_presence_of :vimeo
	
	has_and_belongs_to_many :tags
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/colophon_controller.rb
class ColophonController < ApplicationController
	
	before_filter :authenticate
	
	def home
		
		@introduction_video = Tag.where(:title => 'Introduction').order(:created_at).first.videos.first
		@inspiration_video = Tag.where(:title => 'Inspiration').order(:created_at).first.videos.first
		@challenge_video = Tag.where(:title => 'Challenge').order(:created_at).first.videos.first
		
		@post = Post.feature.first
		
	end
	
	def story
		@stories = (Post.all + Video.all).sort_by(&:created_at).reverse
	end
	
	 protected

	  def authenticate
			if Rails.env.production?
	    	authenticate_or_request_with_http_basic do |username, password|
		      password == "eypurpose"
		    end
			else
				true
			end
	  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/colophon/home.html.erb
<section id="introduction" class="container">
	<% unless @introduction_video.nil? %>
	<iframe id="vimeoembed" src="http://player.vimeo.com/video/<%= @introduction_video.vimeo %>?title=0&amp;byline=0&amp;portrait=0&amp;color=FFD300" width="620" height="340" frameborder="0"></iframe>
	<% end %>
	<div class="panel">
		<p>As we've been working on our financial plan, we've noticed that we tend to talk about our business in terms of the outputs. We don't talk enough about the things that make us who we are &ndash; what we do and why we do it.</p>
		<p>At our core, we're a team of smart people working together to solve the most pressing problems for world class organisations.</p>
		<p>So we've started a collaborative project to open up a dialogue around what we do at UK&amp;I Advisory and why it's important &ndash; our purpose. To re-connect us with our work and to collectively shape a story about where we're heading. Please get involved and share your ideas, experiences and energy.</p>
	</div>
</section>

<section id="timeline">
	<div class="container">
		<h2>The Journey</h2>
		<ol id="the_journey">
			<li class="step_1">Senior leadership team</li>
			<li class="step_2">Partner team</li>
			<li class="step_3">Workshops</li>
			<li class="step_4">Town halls</li>
			<li class="step_5">Web forum</li>
			<li class="step_6">Clients</li>
			<li class="step_7">The story</li>	
		</ol>
	</div>
</section>

<div class="grid_three container" id="blog">
	<section id="inspiration" class="panel">
		<h2>Inspiration</h2>
		<p>Ideas to inspire our thinking<br /><br /></p>
		<% unless @inspiration_video.nil? %>
		<iframe id="vimeoembed" src="http://player.vimeo.com/video/<%= @inspiration_video.vimeo %>?title=0&amp;byline=0&amp;portrait=0&amp;color=FFD300" width="300" height="160" frameborder="0"></iframe>
		<% end %>
	</section>
	<section id="challenge" class="panel">
		<h2>Challenge</h2>
		<p>Ideas to provoke: the interconnectedness of a globalised society</p>
		<% unless @challenge_video.nil? %>
		<iframe id="vimeoembed" src="http://player.vimeo.com/video/<%= @challenge_video.vimeo %>?title=0&amp;byline=0&amp;portrait=0&amp;color=FFD300" width="300" height="160" frameborder="0"></iframe>
		<% end %>
	</section>
	<section id="story" class="panel">
		<h2>Our story</h2>
		<p>Follow the updates and emerging story from this collaborative project</p>
		<% if @post.present? %>
		<article>
			<h3><%= link_to @post.title, story_path %></h3>
			<%= simple_format(auto_link(@post.excerpt)) %>
		</article>
		<% end %>
	</section>
</div>

<section id="discussion" class="container">
	
	<h2>Start a conversation</h2>
	
	<iframe id="forum_embed"
	 src="javascript:void(0)"
	 scrolling="yes"
	 frameborder="0"
	 width="940"
	 height="450">
	</iframe>

	<script type="text/javascript">
	 document.getElementById("forum_embed").src =
	  "https://groups.google.com/forum/embed/?place=forum/ourpurpose&hidesubject=true&hideforumtitle=true&showpopout=false&showtabs=false&showpopout=true&theme=default&parenturl=" +
	  encodeURIComponent(window.location.href) + "#!forum/ourpurpose";
	</script>
	
</section>

app/views/colophon/story.html.erb
<section id="stories" class="container">
	
	<% if @stories.any? %>
	
		<% @stories.each do |story| %>
			
			<article>
				
				<% if story.class == Post %>
					<h3><%= story.title %></h3>
					<%= simple_format(auto_link(story.body)) %>
					
					<% unless story.vimeo.nil? %>
						<iframe id="vimeoembed" src="http://player.vimeo.com/video/<%= story.vimeo %>?title=0&amp;byline=0&amp;portrait=0&amp;color=FFD300" width="940" height="520" frameborder="0"></iframe>
					<% end %>
					
				<% elsif story.class == Video %>
					<h3><%= story.tags.first.title %></h3>
				
					<iframe id="vimeoembed" src="http://player.vimeo.com/video/<%= story.vimeo %>?title=0&amp;byline=0&amp;portrait=0&amp;color=FFD300" width="940" height="520" frameborder="0"></iframe>
				<% end %>
				
			</article>
			
		<% end %>
		
	<% end %>
	
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		
		<title>Our Purpose &mdash; UK&amp;I Advisory &mdash; Ernst &amp; Young</title>
		
		<meta name="description" content="Our Purpose" />
		<meta name="keywords" content="our purpose, ernst, young" />
		<link rel="shortcut icon" href="/favicon.ico?v1" />
		<meta name="robots" content="noindex,nofollow" />
	
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
				
		<% if Rails.env.production? %>
			<script type="text/javascript">

			  var _gaq = _gaq || [];
			  _gaq.push(['_setAccount', 'UA-35888185-1']);
			  _gaq.push(['_trackPageview']);

			  (function() {
			    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			  })();

			</script>
		<% end %>
				
	</head>
	<body class="<%= "section_#{params[:controller].parameterize.underscore} view_#{params[:action]}"%>">

		<header class="container">
			<h1>
				<strong>UK&amp;I Advisory</strong><br />
				<% if params[:action] == "home" %>
					Our Purpose 
				<% else %>
					<%= link_to "Our Purpose", root_path %>
					<span><%= params[:action].titlecase %></span>
				<% end %>
				
			</h1>
		</header>

		<div id="primary_content">
			<%= yield %>
		</div>
		
		<footer class="container">
			<p>A Pipeline Project 2012</p>
		</footer>

	</body>
</html>